### PR TITLE
Configurability bugfixes

### PR DESCRIPTION
**Pull request by jayzes**

### CODE REVIEW

**Comment by jedschneider** [comment]
@wvmitchell I assume these fixes were made to get adminsimple to work with rails 4.x?

**Comment by wvmitchell** [comment]
Yup, looks like it

**Comment by jedschneider** [comment]
did you ever get it running with rails 4?

**Comment by wvmitchell** [comment]
Ya, the whole project was migrated to rails 4

On Mon, Jun 29, 2015 at 11:10 AM, Jed Schneider <notifications@github.com>
wrote:

> did you ever get it running with rails 4?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/modeset/adminsimple/pull/3#issuecomment-116763763>.
>



-- 
Will Mitchell
WVM Development
www.wvm-dev.com

**Pull request closed without merging**
